package knowledge

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"sync"
)

// The runtime catalog and internal index are generated by
// scripts/import-master-database.py from the user-maintained master database.
// Keeping them separate preserves the distinction between documented UI
// controls and raw serialized .pgtx evidence.
//
//go:embed pigments_master_catalog.json
var rawMasterCatalog []byte

//go:embed pigments_internal_index.json
var rawInternalIndex []byte

var (
	runtimeOnce sync.Once
	runtimeData RuntimeMasterCatalog
	indexData   RuntimeInternalIndex
	runtimeErr  error
)

type RuntimeMasterCatalog struct {
	SchemaVersion  string                `json:"schema_version"`
	Product        string                `json:"product"`
	TargetVersion  string                `json:"target_version"`
	SourceDatabase RuntimeSourceDatabase `json:"source_database"`
	Statistics     RuntimeStatistics     `json:"statistics"`
	Notes          []string              `json:"notes"`
	Sections       []RuntimeSection      `json:"sections"`
	SampleBrowser  RuntimeSampleBrowser  `json:"sample_browser"`
}

type RuntimeSourceDatabase struct {
	Name                  string `json:"name"`
	SchemaVersion         string `json:"schema_version"`
	DataRevision          string `json:"data_revision"`
	LastUpdated           string `json:"last_updated"`
	PluginBuild           string `json:"plugin_build"`
	VersionKnowledgeState string `json:"version_knowledge_state"`
}

type RuntimeStatistics struct {
	UIControlCount              int            `json:"ui_control_count"`
	ModuleCount                 int            `json:"module_count"`
	MappedUIControlCount        int            `json:"mapped_ui_control_count"`
	AutomaticEditControlCount   int            `json:"automatic_edit_control_count"`
	UniqueMappedInternalIDCount int            `json:"unique_mapped_internal_id_count"`
	InternalParameterCount      int            `json:"internal_parameter_count"`
	PresetValueRowCount         int            `json:"preset_value_row_count"`
	PresetCount                 int            `json:"preset_count"`
	MappingStatusCounts         map[string]int `json:"mapping_status_counts"`
	MappingConfidenceCounts     map[string]int `json:"mapping_confidence_counts"`
}

type RuntimeSection struct {
	ID             string                     `json:"id"`
	Label          string                     `json:"label"`
	EngineTypeID   string                     `json:"engine_type_id"`
	ModuleCategory string                     `json:"module_category"`
	DataStatus     string                     `json:"data_status"`
	Parameters     []RuntimeDocumentedControl `json:"parameters"`
}

type RuntimeDependency struct {
	Condition string `json:"condition_text"`
	Effect    string `json:"effect_text"`
	Status    string `json:"verification_status"`
}

type RuntimeMappingTarget struct {
	ParameterID string `json:"parameter_id"`
	Role        string `json:"role"`
	EngineSlot  string `json:"engine_slot"`
	Condition   string `json:"condition"`
	Transform   string `json:"transform"`
	Legacy      bool   `json:"legacy"`
}

type RuntimeVariant struct {
	Name       string   `json:"variant_name"`
	Minimum    *float64 `json:"min_value"`
	Maximum    *float64 `json:"max_value"`
	Unit       string   `json:"unit"`
	Format     string   `json:"value_format"`
	Activation string   `json:"activation_condition"`
}

type RuntimeDocumentedControl struct {
	ControlID         string                 `json:"control_id"`
	UIName            string                 `json:"ui_name"`
	NormalizedName    string                 `json:"normalized_name"`
	Control           string                 `json:"control"`
	Unit              string                 `json:"unit"`
	Minimum           *float64               `json:"minimum"`
	Maximum           *float64               `json:"maximum"`
	Default           any                    `json:"default"`
	Step              any                    `json:"step"`
	ValueFormat       string                 `json:"value_format"`
	Values            []string               `json:"values"`
	Variants          []RuntimeVariant       `json:"variants"`
	Endpoints         map[string]string      `json:"endpoints"`
	Aliases           []string               `json:"aliases"`
	DataStatus        string                 `json:"data_status"`
	Description       string                 `json:"description"`
	Dependencies      []RuntimeDependency    `json:"dependencies"`
	SourceID          string                 `json:"source_id"`
	EvidenceStatuses  []string               `json:"evidence_statuses"`
	CanonicalIDs      []string               `json:"canonical_ids"`
	MappingTargets    []RuntimeMappingTarget `json:"mapping_targets"`
	MappingStatus     string                 `json:"mapping_status"`
	MappingConfidence string                 `json:"mapping_confidence"`
	AutomaticEdit     bool                   `json:"automatic_edit"`
	ConversionStatus  string                 `json:"conversion_status"`
	MappingNotes      string                 `json:"mapping_notes"`
}

type RuntimeSampleBrowser struct {
	Banks          []RuntimeSampleBank  `json:"banks"`
	VisibleEntries []RuntimeSampleEntry `json:"visible_entries"`
	Slots          []RuntimeSampleSlot  `json:"slots"`
	Exhaustive     bool                 `json:"exhaustive"`
}

type RuntimeSampleBank struct {
	ID           string `json:"bank_id"`
	DisplayName  string `json:"display_name"`
	DisplayOrder int    `json:"display_order"`
	SourceID     string `json:"source_id"`
	Visibility   string `json:"visibility_status"`
	CompleteList int    `json:"is_complete_list"`
	Notes        string `json:"notes"`
}

type RuntimeSampleEntry struct {
	ID           string `json:"sample_entry_id"`
	BankID       string `json:"bank_id"`
	DisplayName  string `json:"display_name"`
	DisplayOrder int    `json:"display_order"`
	SourceID     string `json:"source_id"`
	Status       string `json:"entry_status"`
	Notes        string `json:"notes"`
}

type RuntimeSampleSlot struct {
	ID    string `json:"slot_id"`
	Label string `json:"slot_label"`
	Order int    `json:"slot_order"`
	Notes string `json:"notes"`
}

// Backward-compatible aliases used by the generated browser catalog types.
// They intentionally point to the compact runtime structures rather than
// duplicating the full source-database schema in the application binary.
type MasterSampleBank = RuntimeSampleBank
type MasterSampleEntry = RuntimeSampleEntry
type MasterVariant = RuntimeVariant
type MasterDependency = RuntimeDependency

type RuntimeInternalIndex struct {
	SchemaVersion          string                    `json:"schema_version"`
	SourceDatabaseRevision string                    `json:"source_database_revision"`
	InternalParameters     []MasterInternalParameter `json:"internal_parameters"`
}

type MasterInternalParameter struct {
	ID                 string   `json:"id"`
	Namespace          string   `json:"namespace"`
	Subsystem          string   `json:"subsystem"`
	SlotIndex          *int     `json:"slot_index"`
	FamilyHint         string   `json:"family_hint"`
	PresenceCount      int      `json:"presence_count"`
	DistinctValueCount int      `json:"distinct_observed_value_count"`
	ObservedMinimum    *float64 `json:"observed_min"`
	ObservedMaximum    *float64 `json:"observed_max"`
	ValueDomain        string   `json:"value_domain"`
}

type MasterSummary struct {
	Name                        string `json:"name"`
	SchemaVersion               string `json:"schema_version"`
	DataRevision                string `json:"data_revision"`
	LastUpdated                 string `json:"last_updated"`
	PluginBaselineVersion       string `json:"plugin_baseline_version,omitempty"`
	PluginLatestListedVersion   string `json:"plugin_latest_listed_version"`
	ObservedPluginBuild         string `json:"observed_plugin_build"`
	VersionKnowledgeState       string `json:"version_knowledge_state"`
	RevisionCount               int    `json:"revision_count,omitempty"`
	EngineTypeCount             int    `json:"engine_type_count,omitempty"`
	ModuleCount                 int    `json:"module_count"`
	DocumentedControlCount      int    `json:"documented_control_count"`
	MappedUIControlCount        int    `json:"mapped_ui_control_count"`
	AutomaticEditControlCount   int    `json:"automatic_edit_control_count"`
	UniqueMappedInternalIDCount int    `json:"unique_mapped_internal_id_count"`
	SampleBankCount             int    `json:"sample_bank_count"`
	SampleEntryCount            int    `json:"sample_entry_count"`
	ObservedStateCount          int    `json:"observed_state_count,omitempty"`
	PresetCount                 int    `json:"preset_count"`
	InternalParameterCount      int    `json:"internal_parameter_count"`
	PresetParameterValueRows    int    `json:"preset_parameter_value_rows"`
	SerializedObjectTypeCount   int    `json:"serialized_object_type_count,omitempty"`
	EmbeddedResourceCount       int    `json:"embedded_resource_count,omitempty"`
	ExplicitMappedInternalIDs   int    `json:"explicit_mapped_internal_ids"`
	ControlsWithNumericRange    int    `json:"controls_with_numeric_range"`
	ControlsAwaitingCalibration int    `json:"controls_awaiting_calibration"`
	ControlsMissingRanges       int    `json:"controls_missing_ranges"`
	SelectorsMissingOptions     int    `json:"selectors_missing_options"`
}

type MasterSearchResult struct {
	Kind                 string                 `json:"kind"`
	ID                   string                 `json:"id"`
	DisplayName          string                 `json:"display_name"`
	Section              string                 `json:"section,omitempty"`
	ModuleID             string                 `json:"module_id,omitempty"`
	ModuleName           string                 `json:"module_name,omitempty"`
	EngineType           string                 `json:"engine_type,omitempty"`
	Namespace            string                 `json:"namespace,omitempty"`
	Subsystem            string                 `json:"subsystem,omitempty"`
	FamilyHint           string                 `json:"family_hint,omitempty"`
	ControlType          string                 `json:"control_type,omitempty"`
	Unit                 string                 `json:"unit,omitempty"`
	ValueFormat          string                 `json:"value_format,omitempty"`
	Minimum              *float64               `json:"minimum,omitempty"`
	Maximum              *float64               `json:"maximum,omitempty"`
	Options              []string               `json:"options,omitempty"`
	Endpoints            map[string]string      `json:"endpoints,omitempty"`
	DataStatus           string                 `json:"data_status,omitempty"`
	MappingStatus        string                 `json:"mapping_status,omitempty"`
	MappingConfidence    string                 `json:"mapping_confidence,omitempty"`
	AutomaticEdit        bool                   `json:"automatic_edit"`
	ConversionStatus     string                 `json:"conversion_status,omitempty"`
	Description          string                 `json:"description,omitempty"`
	Notes                string                 `json:"notes,omitempty"`
	Aliases              []string               `json:"aliases,omitempty"`
	Dependencies         []RuntimeDependency    `json:"dependencies,omitempty"`
	DependencyCount      int                    `json:"dependency_count,omitempty"`
	EvidenceCount        int                    `json:"evidence_count,omitempty"`
	CanonicalIDs         []string               `json:"canonical_ids,omitempty"`
	MappingTargets       []RuntimeMappingTarget `json:"mapping_targets,omitempty"`
	PresenceCount        int                    `json:"presence_count,omitempty"`
	DistinctValueCount   int                    `json:"distinct_value_count,omitempty"`
	ObservedMinimum      *float64               `json:"observed_minimum,omitempty"`
	ObservedMaximum      *float64               `json:"observed_maximum,omitempty"`
	ObservedMin          *float64               `json:"observed_min,omitempty"`
	ObservedMax          *float64               `json:"observed_max,omitempty"`
	ValueDomain          string                 `json:"value_domain,omitempty"`
	CompilerCanonicalIDs []string               `json:"compiler_canonical_ids,omitempty"`
	Score                int                    `json:"-"`
}

func loadRuntime() (*RuntimeMasterCatalog, *RuntimeInternalIndex, error) {
	runtimeOnce.Do(func() {
		if err := json.Unmarshal(rawMasterCatalog, &runtimeData); err != nil {
			runtimeErr = fmt.Errorf("parse embedded master catalog: %w", err)
			return
		}
		if err := json.Unmarshal(rawInternalIndex, &indexData); err != nil {
			runtimeErr = fmt.Errorf("parse embedded internal index: %w", err)
			return
		}
		if runtimeData.Statistics.UIControlCount == 0 || len(runtimeData.Sections) == 0 || len(indexData.InternalParameters) == 0 {
			runtimeErr = fmt.Errorf("embedded Pigments runtime knowledge is incomplete")
		}
	})
	if runtimeErr != nil {
		return nil, nil, runtimeErr
	}
	return &runtimeData, &indexData, nil
}

func MasterDatabaseJSON() []byte {
	return append([]byte(nil), rawMasterCatalog...)
}

func GetMasterSummary() MasterSummary {
	catalog, index, err := loadRuntime()
	if err != nil {
		return MasterSummary{}
	}
	withRange := 0
	missingRanges := 0
	missingOptions := 0
	awaiting := 0
	for _, section := range catalog.Sections {
		for _, control := range section.Parameters {
			hasRange := control.Minimum != nil && control.Maximum != nil
			if !hasRange {
				for _, variant := range control.Variants {
					if variant.Minimum != nil && variant.Maximum != nil {
						hasRange = true
						break
					}
				}
			}
			if hasRange {
				withRange++
			}
			if isContinuousControl(control.Control) && !hasRange {
				missingRanges++
			}
			if isSelectorControl(control.Control) && len(control.Values) == 0 {
				missingOptions++
			}
			if !control.AutomaticEdit {
				awaiting++
			}
		}
	}
	return MasterSummary{
		Name:                        catalog.SourceDatabase.Name,
		SchemaVersion:               catalog.SourceDatabase.SchemaVersion,
		DataRevision:                catalog.SourceDatabase.DataRevision,
		LastUpdated:                 catalog.SourceDatabase.LastUpdated,
		PluginLatestListedVersion:   catalog.TargetVersion,
		ObservedPluginBuild:         catalog.SourceDatabase.PluginBuild,
		VersionKnowledgeState:       catalog.SourceDatabase.VersionKnowledgeState,
		ModuleCount:                 catalog.Statistics.ModuleCount,
		DocumentedControlCount:      catalog.Statistics.UIControlCount,
		MappedUIControlCount:        catalog.Statistics.MappedUIControlCount,
		AutomaticEditControlCount:   catalog.Statistics.AutomaticEditControlCount,
		UniqueMappedInternalIDCount: catalog.Statistics.UniqueMappedInternalIDCount,
		SampleBankCount:             len(catalog.SampleBrowser.Banks),
		SampleEntryCount:            len(catalog.SampleBrowser.VisibleEntries),
		PresetCount:                 catalog.Statistics.PresetCount,
		InternalParameterCount:      len(index.InternalParameters),
		PresetParameterValueRows:    catalog.Statistics.PresetValueRowCount,
		ExplicitMappedInternalIDs:   catalog.Statistics.UniqueMappedInternalIDCount,
		ControlsWithNumericRange:    withRange,
		ControlsAwaitingCalibration: awaiting,
		ControlsMissingRanges:       missingRanges,
		SelectorsMissingOptions:     missingOptions,
	}
}

func isContinuousControl(controlType string) bool {
	switch controlType {
	case "continuous_knob", "continuous_or_stepped_knob", "numeric_knob", "numeric_field", "continuous_labeled_knob", "continuous_crossfade_knob", "dual_unit_knob":
		return true
	default:
		return false
	}
}

func isSelectorControl(controlType string) bool {
	switch controlType {
	case "enum_selector", "cyclic_enum_selector", "source_selector":
		return true
	default:
		return false
	}
}

func MasterSearch(query string, limit int) []MasterSearchResult {
	catalog, index, err := loadRuntime()
	if err != nil {
		return nil
	}
	if limit <= 0 {
		limit = 80
	}
	if limit > 400 {
		limit = 400
	}
	q := strings.ToLower(strings.TrimSpace(query))
	tokens := meaningfulSearchTokens(q)
	var results []MasterSearchResult

	for _, section := range catalog.Sections {
		for _, control := range section.Parameters {
			dependencyText := make([]string, 0, len(control.Dependencies)*2)
			for _, dependency := range control.Dependencies {
				dependencyText = append(dependencyText, dependency.Condition, dependency.Effect)
			}
			targetIDs := make([]string, 0, len(control.MappingTargets))
			for _, mapping := range control.MappingTargets {
				targetIDs = append(targetIDs, mapping.ParameterID, mapping.Role, mapping.EngineSlot, mapping.Condition)
			}
			text := strings.ToLower(strings.Join([]string{
				control.ControlID, control.UIName, control.NormalizedName, control.Control,
				control.Unit, control.ValueFormat, strings.Join(control.Values, " "),
				strings.Join(control.Aliases, " "), control.DataStatus, control.Description,
				strings.Join(dependencyText, " "), strings.Join(control.CanonicalIDs, " "),
				strings.Join(targetIDs, " "), control.MappingStatus, control.MappingConfidence,
				control.ConversionStatus, control.MappingNotes, section.ID, section.Label,
				section.EngineTypeID, section.ModuleCategory,
			}, " "))
			score := searchScore(q, tokens, text, control.ControlID, control.UIName)
			if q == "" {
				score = 10
			}
			if score <= 0 {
				continue
			}
			description := strings.TrimSpace(control.Description)
			if description == "" {
				description = strings.TrimSpace(control.MappingNotes)
			}
			canonical := append([]string(nil), control.CanonicalIDs...)
			if len(canonical) == 0 {
				canonical = compilerIDsForControl(control.ControlID)
			}
			results = append(results, MasterSearchResult{
				Kind:                 "documented_ui_control",
				ID:                   control.ControlID,
				DisplayName:          control.UIName,
				Section:              section.Label,
				ModuleID:             section.ID,
				ModuleName:           section.Label,
				EngineType:           section.EngineTypeID,
				ControlType:          control.Control,
				Unit:                 control.Unit,
				ValueFormat:          control.ValueFormat,
				Minimum:              control.Minimum,
				Maximum:              control.Maximum,
				Options:              append([]string(nil), control.Values...),
				Endpoints:            cloneStringMap(control.Endpoints),
				DataStatus:           control.DataStatus,
				MappingStatus:        control.MappingStatus,
				MappingConfidence:    control.MappingConfidence,
				AutomaticEdit:        control.AutomaticEdit,
				ConversionStatus:     control.ConversionStatus,
				Description:          description,
				Notes:                control.MappingNotes,
				Aliases:              append([]string(nil), control.Aliases...),
				Dependencies:         append([]RuntimeDependency(nil), control.Dependencies...),
				DependencyCount:      len(control.Dependencies),
				EvidenceCount:        len(control.EvidenceStatuses),
				CanonicalIDs:         canonical,
				MappingTargets:       append([]RuntimeMappingTarget(nil), control.MappingTargets...),
				CompilerCanonicalIDs: canonical,
				Score:                score + 35,
			})
		}
	}

	// The raw 3,525-ID index is intentionally queried only after text is entered.
	if q != "" {
		for _, parameter := range index.InternalParameters {
			text := strings.ToLower(strings.Join([]string{
				parameter.ID, parameter.Namespace, parameter.Subsystem,
				parameter.FamilyHint, parameter.ValueDomain,
			}, " "))
			score := searchScore(q, tokens, text, parameter.ID, parameter.FamilyHint)
			if score <= 0 {
				continue
			}
			results = append(results, MasterSearchResult{
				Kind:               "observed_internal_parameter",
				ID:                 parameter.ID,
				DisplayName:        parameter.ID,
				Section:            parameter.Subsystem,
				EngineType:         parameter.Namespace,
				Namespace:          parameter.Namespace,
				Subsystem:          parameter.Subsystem,
				FamilyHint:         parameter.FamilyHint,
				MappingStatus:      "observed_unmapped_or_overlay_mapped",
				AutomaticEdit:      false,
				Description:        "Exact ID observed in imported Pigments .pgtx state. Observed values do not prove the visible control, unit, range, or conversion curve.",
				PresenceCount:      parameter.PresenceCount,
				DistinctValueCount: parameter.DistinctValueCount,
				ObservedMinimum:    parameter.ObservedMinimum,
				ObservedMaximum:    parameter.ObservedMaximum,
				ObservedMin:        parameter.ObservedMinimum,
				ObservedMax:        parameter.ObservedMaximum,
				ValueDomain:        parameter.ValueDomain,
				Score:              score,
			})
		}
		for _, bank := range catalog.SampleBrowser.Banks {
			text := strings.ToLower(bank.ID + " " + bank.DisplayName + " " + bank.Notes)
			score := searchScore(q, tokens, text, bank.ID, bank.DisplayName)
			if score > 0 {
				results = append(results, MasterSearchResult{Kind: "sample_bank", ID: bank.ID, DisplayName: bank.DisplayName, Section: "Sample Browser", DataStatus: bank.Visibility, Description: bank.Notes, Score: score})
			}
		}
		for _, sample := range catalog.SampleBrowser.VisibleEntries {
			text := strings.ToLower(sample.ID + " " + sample.DisplayName + " " + sample.BankID + " " + sample.Notes)
			score := searchScore(q, tokens, text, sample.ID, sample.DisplayName)
			if score > 0 {
				results = append(results, MasterSearchResult{Kind: "sample_entry", ID: sample.ID, DisplayName: sample.DisplayName, Section: sample.BankID, DataStatus: sample.Status, Description: sample.Notes, Score: score})
			}
		}
	}

	sort.SliceStable(results, func(i, j int) bool {
		if results[i].Score != results[j].Score {
			return results[i].Score > results[j].Score
		}
		if results[i].Kind != results[j].Kind {
			return results[i].Kind < results[j].Kind
		}
		return results[i].ID < results[j].ID
	})
	if len(results) > limit {
		results = results[:limit]
	}
	return results
}

func searchScore(query string, tokens []string, text, exactID, displayName string) int {
	if query == "" {
		return 1
	}
	score := 0
	if strings.EqualFold(query, exactID) {
		score += 2000
	}
	if strings.EqualFold(query, displayName) {
		score += 1000
	}
	if strings.Contains(text, query) {
		score += 250
	}
	matched := 0
	for _, token := range tokens {
		if strings.Contains(text, token) {
			matched++
			score += 25
		}
	}
	if matched == 0 && score == 0 {
		return 0
	}
	if len(tokens) > 1 && matched == len(tokens) {
		score += 75
	}
	return score
}

func meaningfulSearchTokens(query string) []string {
	stop := map[string]bool{
		"a": true, "an": true, "and": true, "are": true, "as": true, "at": true,
		"be": true, "by": true, "create": true, "current": true, "for": true,
		"from": true, "in": true, "into": true, "is": true, "it": true,
		"make": true, "more": true, "my": true, "new": true, "of": true,
		"on": true, "or": true, "preset": true, "sound": true, "than": true,
		"that": true, "the": true, "this": true, "to": true, "use": true,
		"with": true,
	}
	aliases := map[string][]string{
		"bitcrush":     {"bitcrush", "bit crush", "decimate", "bit depth"},
		"bitcrusher":   {"bitcrush", "bit crush", "decimate", "bit depth"},
		"wavefolding":  {"wavefold", "fold"},
		"wavefold":     {"wavefold", "fold"},
		"ringmod":      {"ring mod", "ringmod"},
		"sampleengine": {"sample engine", "samplegranularosc"},
		"wavetable":    {"wavetable", "wtosc"},
		"analog":       {"analog", "va3osc"},
		"granular":     {"granular", "grain"},
	}
	seen := map[string]bool{}
	var tokens []string
	for _, raw := range strings.FieldsFunc(query, func(r rune) bool {
		return !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') && r != '_' && r != '-'
	}) {
		token := strings.TrimSpace(raw)
		if token == "" || stop[token] || (len(token) < 3 && token != "fm" && token != "fx") {
			continue
		}
		values := []string{token}
		if extra, ok := aliases[token]; ok {
			values = extra
		}
		for _, value := range values {
			if !seen[value] {
				seen[value] = true
				tokens = append(tokens, value)
			}
		}
	}
	return tokens
}

func cloneStringMap(source map[string]string) map[string]string {
	if len(source) == 0 {
		return nil
	}
	copyMap := make(map[string]string, len(source))
	for key, value := range source {
		copyMap[key] = value
	}
	return copyMap
}

func MasterPromptSummary(query string, limit int) any {
	catalog, _, err := loadRuntime()
	if err != nil {
		return map[string]any{"error": err.Error()}
	}
	return map[string]any{
		"database":         GetMasterSummary(),
		"catalog_notes":    catalog.Notes,
		"relevant_records": MasterSearch(query, limit),
		"interpretation_rules": []string{
			"automatic_edit=true authorizes conservative numeric addressing, not an exact displayed-unit curve unless conversion_status says calibrated.",
			"Candidate enums, conditional multi-parameter controls, UI-only controls, asset selectors, and inverse-semantics controls must not be changed automatically.",
			"A raw serialized ID proves occurrence in imported preset state, not which visible control it represents.",
			"Only canonical IDs from automatic-edit controls, the curated compiler catalog, or exact IDs already present in the current preset may be mutated.",
		},
	}
}

func MasterDatabaseSummary() map[string]any {
	catalog, _, err := loadRuntime()
	if err != nil {
		return map[string]any{"ready": false, "error": err.Error()}
	}
	summary := GetMasterSummary()
	return map[string]any{
		"ready":    true,
		"metadata": catalog.SourceDatabase,
		"summary": map[string]any{
			"module_count":                       summary.ModuleCount,
			"documented_control_count":           summary.DocumentedControlCount,
			"mapped_ui_control_count":            summary.MappedUIControlCount,
			"automatic_edit_control_count":       summary.AutomaticEditControlCount,
			"unique_mapped_internal_id_count":    summary.UniqueMappedInternalIDCount,
			"internal_parameter_count":           summary.InternalParameterCount,
			"observed_value_row_count":           summary.PresetParameterValueRows,
			"preset_parameter_value_rows":        summary.PresetParameterValueRows,
			"preset_count":                       summary.PresetCount,
			"sample_bank_count":                  summary.SampleBankCount,
			"sample_entry_count":                 summary.SampleEntryCount,
			"explicit_mapped_internal_ids":       summary.ExplicitMappedInternalIDs,
			"controls_with_numeric_range":        summary.ControlsWithNumericRange,
			"controls_awaiting_calibration":      summary.ControlsAwaitingCalibration,
			"continuous_controls_missing_ranges": summary.ControlsMissingRanges,
			"selectors_missing_options":          summary.SelectorsMissingOptions,
		},
		"statistics": catalog.Statistics,
	}
}

func PublicMasterKnowledge() map[string]any {
	catalog, _, err := loadRuntime()
	if err != nil {
		return map[string]any{"ready": false, "error": err.Error()}
	}
	result := MasterDatabaseSummary()
	var controls []RuntimeDocumentedControl
	for _, section := range catalog.Sections {
		controls = append(controls, section.Parameters...)
	}
	result["source_database"] = catalog.SourceDatabase
	result["notes"] = catalog.Notes
	result["sections"] = catalog.Sections
	result["documented_controls"] = controls
	result["sample_banks"] = catalog.SampleBrowser.Banks
	result["sample_library_entries"] = catalog.SampleBrowser.VisibleEntries
	result["sample_slots"] = catalog.SampleBrowser.Slots
	result["sample_browser_exhaustive"] = catalog.SampleBrowser.Exhaustive
	result["disclosure"] = "The raw 3,525-ID inventory and 15,975 preset-value rows remain server-side. Search results expose bounded evidence only."
	return result
}

func SearchMaster(query string, limit int) []MasterSearchResult {
	return MasterSearch(query, limit)
}
